package atlasCompose.ui

import androidx.compose.runtime.MonotonicFrameClock
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.nativeKeyCode
import androidx.compose.ui.input.key.nativeKeyLocation
import androidx.compose.ui.platform.InfiniteAnimationPolicy

@OptIn(ExperimentalComposeUiApi::class)
private class Key {
    val Key.ss:Any get() = this.apply {
        this.keyCode
        this.nativeKeyCode
        this.nativeKeyLocation
    }
    init {
        Key.apply {
            Unknown
            Home
            Help
            DirectionUp
            DirectionDown
            DirectionLeft
            DirectionRight
            Zero
            One
            Two
            Three
            Four
            Five
            Six
            Seven
            Eight
            Nine
            Plus
            Minus
            Multiply
            Equals
            Pound
            A
            B
            C
            D
            E
            F
            G
            H
            I
            J
            K
            L
            M
            N
            O
            P
            Q
            R
            S
            T
            U
            V
            W
            X
            Y
            Z
            Comma
            Period
            AltLeft
            AltRight
            ShiftLeft
            ShiftRight
            Tab
            Spacebar
            Enter
            Backspace
            Delete
            Escape
            CtrlLeft
            CtrlRight
            CapsLock
            ScrollLock
            MetaLeft
            MetaRight
            PrintScreen
            Insert
            Cut
            Copy
            Paste
            Grave
            LeftBracket
            RightBracket
            Slash
            Backslash
            Semicolon
            Apostrophe
            At
            PageUp
            PageDown
            F1
            F2
            F3
            F4
            F5
            F6
            F7
            F8
            F9
            F10
            F11
            F12
            NumLock
            NumPad0
            NumPad1
            NumPad2
            NumPad3
            NumPad4
            NumPad5
            NumPad6
            NumPad7
            NumPad8
            NumPad9
            NumPadDivide
            NumPadMultiply
            NumPadSubtract
            NumPadAdd
            NumPadDot
            NumPadComma
            NumPadEnter
            NumPadEquals
            NumPadLeftParenthesis
            NumPadRightParenthesis
            MoveHome
            MoveEnd
            SoftLeft
            SoftRight
            Back
            NavigatePrevious
            NavigateNext
            NavigateIn
            NavigateOut
            SystemNavigationUp
            SystemNavigationDown
            SystemNavigationLeft
            Call
            EndCall
            DirectionCenter
            DirectionUpLeft
            DirectionDownLeft
            DirectionUpRight
            DirectionDownRight
            VolumeUp
            VolumeDown
            Power
            Camera
            Clear
            Symbol
            Browser
            Envelope
            Function
            Break
            Number
            HeadsetHook
            Focus
            Menu
            Notification
            Search
            PictureSymbols
            SwitchCharset
            ButtonA
            ButtonB
            ButtonC
            ButtonX
            ButtonY
            ButtonZ
            ButtonL1
            ButtonR1
            ButtonL2
            ButtonR2
            ButtonThumbLeft
            ButtonThumbRight
            ButtonStart
            ButtonSelect
            ButtonMode
            Button1
            Button2
            Button3
            Button4
            Button5
            Button6
            Button7
            Button8
            Button9
            Button10
            Button11
            Button12
            Button13
            Button14
            Button15
            Button16
            Forward
            MediaPlay
            MediaPause
            MediaPlayPause
            MediaStop
            MediaRecord
            MediaNext
            MediaPrevious
            MediaRewind
            MediaFastForward
            MediaClose
            MediaAudioTrack
            MediaEject
            MediaTopMenu
            MediaSkipForward
            MediaSkipBackward
            MediaStepForward
            MediaStepBackward
            MicrophoneMute
            VolumeMute
            Info
            ChannelUp
            ChannelDown
            ZoomIn
            ZoomOut
            Tv
            Window
            Guide
            Dvr
            Bookmark
            Captions
            Settings
            TvPower
            TvInput
            SetTopBoxPower
            SetTopBoxInput
            AvReceiverPower
            AvReceiverInput
            ProgramRed
            ProgramGreen
            ProgramYellow
            ProgramBlue
            AppSwitch
            LanguageSwitch
            MannerMode
            Toggle2D3D
            Contacts
            Calendar
            Music
            Calculator
            ZenkakuHankaru
            Eisu
            Muhenkan
            Henkan
            KatakanaHiragana
            Yen
            Ro
            Kana
            Assist
            BrightnessDown
            BrightnessUp
            Sleep
            WakeUp
            SoftSleep
            Pairing
            LastChannel
            TvDataService
            VoiceAssist
            TvRadioService
            TvTeletext
            TvNumberEntry
            TvTerrestrialAnalog
            TvTerrestrialDigital
            TvSatellite
            TvSatelliteBs
            TvSatelliteCs
            TvSatelliteService
            TvNetwork
            TvAntennaCable
            TvInputHdmi1
            TvInputHdmi2
            TvInputHdmi3
            TvInputHdmi4
            TvInputComposite1
            TvInputComposite2
            TvInputComponent1
            TvInputComponent2
            TvInputVga1
            TvAudioDescription
            TvAudioDescriptionMixingVolumeUp
            TvAudioDescriptionMixingVolumeDown
            TvZoomMode
            TvContentsMenu
            TvMediaContextMenu
            TvTimerProgramming
            StemPrimary
            Stem1
            Stem2
            Stem3
            AllApps
            Refresh
            ThumbsUp
            ThumbsDown
            ProfileSwitch
        }
    }
}